service_name: Hoofdwegen
description: Hoofdwegen
organization:
  name: Gemeente Amsterdam
  ooid: 25698
api_type: rest_json
api_authentication: none
environments:
- name: production
  api_url: https://api.data.amsterdam.nl/v1/hoofdroutes
  specification_url: https://api.data.amsterdam.nl/v1/hoofdroutes/openapi.json
  documentation_url: https://api.data.amsterdam.nl/v1/docs/datasets/hoofdroutes.html
contact:
  email: dataplatform@amsterdam.nl
  url: https://api.data.amsterdam.nl/api/
terms_of_use:
  government_only: false
  pay_per_use: false
  uptime_guarantee: 0
